const Data = [
    {
        id: 1,
        country: 'Italija',
        date: '2023 01 05 - 01 12',
        category: 'Italija',
        price: 950,
        img: 'https://www.snowindustrynews.com/media/3478/audi-nines-wide.jpg',
        desc: `Livigno (tarti livinjo) yra visus metus veikiantis kurortas, kuris žiemą tampa vienu lankomiausių visose Alpėse.`,
        camp: 'Stovykla #1 @ Livingo 2023',
    },
    {
        id: 2,
        country: 'Prancūzija',
        date: '2023 01 10 - 01 17',
        category: 'Prancūzija',
        price: 750,
        img: 'https://usskiandsnowboard.org/sites/default/files/styles/metatagimage/public/images/news-articles/hero-image/2019-06/ChrisCorningHero_0.jpg?itok=24J-nxul',
        desc: `Trasų aukštis čia prasideda nuo 1650 m., o didžiausias trasų aukštis siekia net 3600 m.`,
        camp: 'Stovykla #2 @ LES 2 EX 2023',
    },
    {
        id: 3,
        country: 'Sakartvelas',
        date: '2023 02 15 - 02 22',
        category: 'Sakartvelas',
        price: 500,
        img: 'https://www.ispo.com/sites/default/files/2018-11/Planai-roland-haschka-qparks.jpg',
        desc: `Gudauri – didžiausias Sakartvelo (Gruzijos) slidinėjimo kurortas, įsikūręs Kazbegi regione, 120 km`,
        camp: 'Stovykla #3 @ GUDAURI 2023',
    },
    {
        id: 4,
        country: 'Sakartvelas',
        date: '2023 01 05 - 01 12',
        category: 'Sakartvelas',
        price: 800,
        img: 'https://as01.epimg.net/deportes_accion/imagenes/2021/04/12/snow/1618223466_873012_1618223736_noticia_normal_recorte1.jpg',
        desc: `Svanetijos regionas užima labai kalnuotas sritis Kaukazo kalnų grandinėje.`,
        camp: 'Stovykla #4 @ SVANETIJA 2023',
    },

    {
        id: 5,
        country: 'Austrija',
        date: '2023 01 05 - 01 12',
        category: 'Austrija',
        price: 980,
        img: 'https://blog.skisolutions.com/wp-content/uploads/2020/02/Avoriaz-Snow-Park.jpg',
        desc: `Slidinėjimo zonose yra nuostabūs nameliai, sniego barai ir vietos vakarėliams.`,
        camp: 'Stovykla #5 @ Apres Ski 2023',
    },

    {
        id: 6,
        country: 'Austrija',
        date: '2023 01 05 - 01 12',
        category: 'Austrija',
        price: 1100,
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3wqbYhXs_se6hwQL7BaZViAhYAwoYON_q04n9oR3g-N3ZgjR1k-U88dUYV2GIYhWDzGA&usqp=CAU',
        desc: `Bad Gaštainas išsiskiria senoviniais viešbučiais derančiais su šiuolaikišku poilsio ir pramogų infrastruktūra`,
        camp: 'Stovykla #6 @ Bad Gastein 2023',
    },
    {
        id: 7,
        country: 'Prancūzija',
        date: '2023 01 05 - 01 12',
        category: 'Prancūzija',
        price: 800,
        img: 'https://as01.epimg.net/deportes_accion/imagenes/2021/04/12/snow/1618223466_873012_1618223736_noticia_normal_recorte1.jpg',
        desc: ` įkurtas prieš daugiau nei 50 metų, vienas seniausių ir prestižiškiausių Prancūzijoje.`,
        camp: 'Stovykla #7 @ LES 2 EX 2023',
    },
    {
        id: 8,
        country: 'Prancūzija',
        date: '2023 01 05 - 01 12',
        category: 'Prancūzija',
        price: 830,
        img: 'https://as01.epimg.net/deportes_accion/imagenes/2021/04/12/snow/1618223466_873012_1618223736_noticia_normal_recorte1.jpg',
        desc: `Courchevel kurorte, suteikia slidininkams ir snieglentininkams galimybę čiuožinėti 150 kilometrų.`,
        camp: 'Stovykla #8 @ Courchevel 2023',
    },
    {
        id: 9,
        country: 'Italija',
        date: '2023 04 22 - 04 29',
        category: 'Italija',
        price: 1300,
        img: 'https://s20084.pcdn.co/wp-content/uploads/2018/03/qc9ptrizoaxpawsxch4v.jpg',
        desc: `Val Gardena ekspertai ir slidininkai mėgėjai Val Gardenos slėnį įvardija kaip vieną geriausių vietų regione`,
        camp: 'Stovykla #9 @ Val Gardena 2023',
    },
    {
        id: 10,
        country: 'Italija',
        date: '2023 03 03 - 03 10',
        category: 'Italija',
        price: 840,
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5LPmFudEhsVdpKcvL4jBRYt1zfjRt8X-eyRB-7AsoL-j2E_Zzk6I5uwZm2KjB5Ryb8Kk&usqp=CAU',
        desc: `Livigno (tarti livinjo) yra visus metus veikiantis kurortas, kuris žiemą tampa vienu lankomiausių visose Alpėse.`,
        camp: 'Stovykla #10 @ Livingo 2023',
    },
]



export default Data;